name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-build-crisp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build tractor-crisp
        run: docker build . -t tractor-crisp

  docker-build-crisp-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build tractor-crisp-user
        run: docker build . -f Dockerfile.work -t tractor-crisp-user

  build-crisp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - run: uv sync

      - run: |
          uv tool install .
          which crisp
  
  build-tools:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        crate:
          - find_unsafe
          - split_ffi_entry_points

    env:
      RUSTFLAGS: "-D warnings"
      RUSTDOCFLAGS: "-D warnings"

    defaults:
      run:
        working-directory: tools/${{ matrix.crate }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: tools/${{ matrix.crate }}

      - run: cargo fmt --check

      - run: cargo check --release

      - run: cargo build --release

      - run: cargo test --release --all-features

      - run: cargo doc --all-features --document-private-items --no-deps
