name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            image: tractor-crisp
          - dockerfile: Dockerfile.work
            image: tractor-crisp-user

    steps:
      - name: Checkout Tractor-Crisp w/ HTTPS w/o submodules
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Configure git for private GitLab submodule
        run: |
          # Set SSH command just for GitLab
          mkdir -p ~/.ssh
          echo "${{ secrets.READ_GITLAB_EXT_GALOIS_COM_TRACTOR_TEST_CORPUS_MIRROR }}" > ~/.ssh/test_corpus_mirror_deploy_key
          chmod 600 ~/.ssh/test_corpus_mirror_deploy_key
          git config --global url."git@gitlab-ext.galois.com:".insteadOf "ssh://git@gitlab-ext.galois.com/"
          git config --global core.sshCommand "ssh -i ~/.ssh/test_corpus_mirror_deploy_key -o StrictHostKeyChecking=no"

      - name: Update submodules
        run: |
          # `--checkout` ensures we check out the `update = none` submodules, too.
          git submodule update --init --checkout --depth 1

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Docker Build
        run: |
          OWNER=${{ github.repository_owner }}
          IMAGE_NAME=ghcr.io/${OWNER,,}/${{ matrix.image }}
          DOCKERFILE=${{ matrix.dockerfile }}

          docker buildx build \
            --cache-from type=registry,ref=${IMAGE_NAME}:cache \
            --cache-to   type=registry,ref=${IMAGE_NAME}:cache,mode=max \
            -f ${DOCKERFILE} \
            -t ${IMAGE_NAME}:latest \
            --push \
            .

  build-crisp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - run: uv sync

      - run: |
          uv tool install .
          which crisp
  
  build-tools:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        crate:
          - find_unsafe
          - split_ffi_entry_points

    env:
      RUSTFLAGS: "-D warnings"
      RUSTDOCFLAGS: "-D warnings"

    defaults:
      run:
        working-directory: tools/${{ matrix.crate }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: tools/${{ matrix.crate }}

      - run: cargo check --release

      - run: cargo build --release

      - run: cargo test --release --all-features

      - run: cargo doc --all-features --document-private-items --no-deps
